"""TRAVELO destination catalog + savage quotes — single source of truth."""

TIER_MULTIPLIERS = {"explorer": 1.0, "elite": 1.65, "legend": 2.8}
TIERS = ["explorer", "elite", "legend"]


def tier_price(base_price: int, tier: str) -> int:
    """Price per person in whole USD for a tier."""
    return int(round(base_price * TIER_MULTIPLIERS[tier]))


DESTINATIONS = [
    {
        "id": "santorini",
        "name": "Santorini",
        "country": "Greece",
        "region": "Europe",
        "tagline": "Where the sun dies beautifully every single night.",
        "description": "Cliff-carved villages in blinding white, caldera sunsets that make grown adults cry, and wine grown in volcanic ash. Santorini isn't a destination — it's a flex.",
        "image": "https://images.unsplash.com/photo-1672622851784-0dbd3df4c088",
        "base_price": 1499,
        "rating": 4.9,
        "duration_days": 6,
        "highlights": ["Oia sunset from a private cliff terrace", "Catamaran raid across the caldera", "Volcanic-ash vineyard tasting", "Red Beach cliff dive"],
    },
    {
        "id": "kyoto",
        "name": "Kyoto",
        "country": "Japan",
        "region": "Asia",
        "tagline": "Ten thousand gates. Zero regrets.",
        "description": "Vermilion torii tunnels, bamboo forests that whisper, geisha districts frozen in time. Kyoto is what happens when a city decides perfection is the minimum standard.",
        "image": "https://images.unsplash.com/photo-1665706896821-319040b81753",
        "base_price": 1799,
        "rating": 4.9,
        "duration_days": 7,
        "highlights": ["Fushimi Inari at dawn — before the crowds exist", "Private tea ceremony in Gion", "Arashiyama bamboo grove", "Kaiseki dinner with a Michelin ghost"],
    },
    {
        "id": "iceland",
        "name": "Iceland",
        "country": "Iceland",
        "region": "Europe",
        "tagline": "The sky is on fire and it's completely normal.",
        "description": "Aurora storms overhead, glaciers you can walk inside, black sand beaches that look like another planet. Iceland doesn't do subtle.",
        "image": "https://images.unsplash.com/photo-1518156959312-07a5380c1261",
        "base_price": 1899,
        "rating": 4.8,
        "duration_days": 6,
        "highlights": ["Northern lights hunt in a super-jeep", "Ice cave descent under Vatnajökull", "Blue Lagoon midnight float", "Golden Circle full assault"],
    },
    {
        "id": "bali",
        "name": "Bali",
        "country": "Indonesia",
        "region": "Asia",
        "tagline": "Paradise with a caffeine addiction.",
        "description": "Emerald rice terraces, cliff temples guarded by monkeys with attitude, sunsets that reset your soul. Bali is the reset button you keep pretending you don't need.",
        "image": "https://images.pexels.com/photos/3067621/pexels-photo-3067621.jpeg",
        "base_price": 1199,
        "rating": 4.7,
        "duration_days": 8,
        "highlights": ["Tegallalang rice terrace sunrise", "Uluwatu cliff temple at golden hour", "Private villa with infinity pool", "Nusa Penida island raid"],
    },
    {
        "id": "swiss-alps",
        "name": "Swiss Alps",
        "country": "Switzerland",
        "region": "Europe",
        "tagline": "The mountains called. We answered for you.",
        "description": "The Matterhorn staring you down, trains that climb through clouds, fondue at 3,000 meters. Switzerland charges premium because it IS premium.",
        "image": "https://images.unsplash.com/photo-1640535258715-2cb15ccd7eae",
        "base_price": 2299,
        "rating": 4.9,
        "duration_days": 7,
        "highlights": ["Matterhorn sunrise from Gornergrat", "Glacier Express panoramic ride", "Zermatt heli-tour", "Alpine spa with peak views"],
    },
    {
        "id": "patagonia",
        "name": "Patagonia",
        "country": "Chile",
        "region": "South America",
        "tagline": "Where the map runs out and legends begin.",
        "description": "Granite towers ripping through storm clouds, turquoise glacier lakes, wind that rearranges your priorities. Patagonia is the final boss of landscapes.",
        "image": "https://images.unsplash.com/photo-1637580980556-085dee659c7e",
        "base_price": 2499,
        "rating": 4.8,
        "duration_days": 9,
        "highlights": ["Torres del Paine W-trek (guided)", "Grey Glacier ice hike", "Puma tracking with rangers", "Estancia asado under the stars"],
    },
    {
        "id": "marrakech",
        "name": "Marrakech",
        "country": "Morocco",
        "region": "Africa",
        "tagline": "A thousand colors. One racing heartbeat.",
        "description": "Labyrinth souks, rooftop mint tea, desert nights an hour away. Marrakech doesn't ask for your attention — it takes it.",
        "image": "https://images.pexels.com/photos/36209321/pexels-photo-36209321.jpeg",
        "base_price": 999,
        "rating": 4.6,
        "duration_days": 5,
        "highlights": ["Medina raid with a local fixer", "Agafay desert dinner camp", "Traditional hammam ritual", "Jardin Majorelle private hour"],
    },
    {
        "id": "maldives",
        "name": "Maldives",
        "country": "Maldives",
        "region": "Asia",
        "tagline": "Fifty shades of blue. Zero shades of stress.",
        "description": "Overwater villas, water so clear it looks rendered, reef sharks as neighbors. The Maldives is what screensavers dream of becoming.",
        "image": "https://images.unsplash.com/photo-1514282401047-d79a71a590e8",
        "base_price": 2999,
        "rating": 5.0,
        "duration_days": 6,
        "highlights": ["Overwater villa with glass floor", "Manta ray night snorkel", "Sandbank private picnic", "Sunset dolphin cruise"],
    },
    {
        "id": "machu-picchu",
        "name": "Machu Picchu",
        "country": "Peru",
        "region": "South America",
        "tagline": "The Incas built it. You just have to show up.",
        "description": "A lost city floating in cloud forest at 2,430 meters. Machu Picchu is proof that humans used to build things worth crossing the planet for.",
        "image": "https://images.unsplash.com/photo-1526392060635-9d6019884377",
        "base_price": 1699,
        "rating": 4.9,
        "duration_days": 7,
        "highlights": ["Sunrise entry through the Sun Gate", "Sacred Valley + Pisac market", "Vistadome panoramic train", "Cusco colonial quarter stay"],
    },
    {
        "id": "dubai",
        "name": "Dubai",
        "country": "UAE",
        "region": "Middle East",
        "tagline": "The future got impatient and built itself a city.",
        "description": "Skyscrapers that ignore physics, desert dunes at the city limits, luxury as a baseline. Dubai is what ambition looks like with an unlimited budget.",
        "image": "https://images.pexels.com/photos/36813102/pexels-photo-36813102.jpeg",
        "base_price": 1599,
        "rating": 4.7,
        "duration_days": 5,
        "highlights": ["Burj Khalifa 148th floor lounge", "Desert safari + dune bashing", "Marina superyacht evening", "Old Dubai gold souk raid"],
    },
    {
        "id": "norwegian-fjords",
        "name": "Norwegian Fjords",
        "country": "Norway",
        "region": "Europe",
        "tagline": "Carved by ice. Claimed by you.",
        "description": "Kilometer-deep fjords, waterfalls falling from the sky, villages clinging to cliffs. Norway is nature showing off and refusing to apologize.",
        "image": "https://images.pexels.com/photos/15979078/pexels-photo-15979078.jpeg",
        "base_price": 2099,
        "rating": 4.8,
        "duration_days": 7,
        "highlights": ["Geirangerfjord silent electric cruise", "Trolltunga guided hike", "Flåm railway descent", "Fjordside cabin with sauna"],
    },
    {
        "id": "tokyo",
        "name": "Tokyo",
        "country": "Japan",
        "region": "Asia",
        "tagline": "Thirty-seven million people. Zero wasted seconds.",
        "description": "Neon canyons, sushi masters with 40-year obsessions, silence in temples two blocks from chaos. Tokyo is the maximum possible city.",
        "image": "https://images.unsplash.com/photo-1536768139911-e290a59011e4",
        "base_price": 1899,
        "rating": 4.8,
        "duration_days": 7,
        "highlights": ["Shibuya crossing from a private rooftop", "Tsukiji dawn omakase", "TeamLab digital art night", "Golden Gai bar crawl with a local"],
    },
    {
        "id": "goa",
        "name": "Goa",
        "country": "India",
        "region": "India",
        "tagline": "Beach by day. Legend by night.",
        "description": "Palm-fringed beaches, Portuguese soul, shacks serving fish curry at sunset and parties that outlast the moon. Goa isn't a place — it's a permanent state of mind.",
        "image": "https://images.pexels.com/photos/32262470/pexels-photo-32262470.jpeg",
        "base_price": 899,
        "rating": 4.7,
        "duration_days": 6,
        "highlights": ["Sunset shack-hop across Anjuna and Vagator", "Old Goa heritage + spice farm raid", "Midnight flea market at Arpora", "Dolphin cruise on the Mandovi"],
    },
    {
        "id": "jaipur",
        "name": "Jaipur",
        "country": "India",
        "region": "India",
        "tagline": "The city that decided pink was a power move.",
        "description": "Honey-colored forts on hilltops, palaces with a thousand windows, bazaars that smell like saffron and ambition. The Pink City doesn't do understatement.",
        "image": "https://images.unsplash.com/photo-1524230699147-7e6f131d021e",
        "base_price": 799,
        "rating": 4.7,
        "duration_days": 5,
        "highlights": ["Amber Fort sunrise before the crowds", "Hawa Mahal facade photo raid", "Royal thali dinner in a haveli", "Johari Bazaar gem hunting"],
    },
    {
        "id": "kerala",
        "name": "Kerala",
        "country": "India",
        "region": "India",
        "tagline": "God's own country. His best work, honestly.",
        "description": "Houseboats gliding through emerald backwaters, tea hills wrapped in mist, ayurveda that resets your entire operating system. Kerala moves slow on purpose.",
        "image": "https://images.pexels.com/photos/14172615/pexels-photo-14172615.jpeg",
        "base_price": 949,
        "rating": 4.8,
        "duration_days": 6,
        "highlights": ["Private houseboat night on Alleppey backwaters", "Munnar tea plantation trek", "Kathakali performance up close", "Ayurvedic massage ritual"],
    },
    {
        "id": "ladakh",
        "name": "Ladakh",
        "country": "India",
        "region": "India",
        "tagline": "The Himalayas' VIP section.",
        "description": "Moonscape passes at 5,000 meters, monasteries clinging to cliffs, Pangong lake changing colors like it's showing off. Ladakh is the trip your lungs remember forever.",
        "image": "https://images.unsplash.com/photo-1635255506105-b74adbd94026",
        "base_price": 1099,
        "rating": 4.9,
        "duration_days": 8,
        "highlights": ["Pangong Tso sunrise camp", "Khardung La pass ride", "Thiksey monastery morning prayers", "Nubra Valley double-hump camel safari"],
    },
    {
        "id": "varanasi",
        "name": "Varanasi",
        "country": "India",
        "region": "India",
        "tagline": "Older than history. Louder than silence.",
        "description": "Five thousand years of continuous life on the Ganges. Fire ceremonies at dusk, boats at dawn, alleys that rearrange themselves. Varanasi doesn't explain itself.",
        "image": "https://images.unsplash.com/photo-1571536802807-30451e3955d8",
        "base_price": 749,
        "rating": 4.6,
        "duration_days": 4,
        "highlights": ["Dawn boat ride past the ghats", "Ganga Aarti fire ceremony front row", "Old city street food crawl", "Sarnath — where Buddha first taught"],
    },
    {
        "id": "udaipur",
        "name": "Udaipur",
        "country": "India",
        "region": "India",
        "tagline": "Venice called. It wants its romance back.",
        "description": "White marble palaces floating on lakes, rooftop dinners over shimmering water, sunsets that turn the whole city gold. Udaipur is a love letter written in stone.",
        "image": "https://images.unsplash.com/photo-1695956353120-54ce5e91632b",
        "base_price": 899,
        "rating": 4.8,
        "duration_days": 5,
        "highlights": ["Lake Pichola sunset cruise", "City Palace private tour", "Rooftop dinner facing the Lake Palace", "Vintage car museum of the Maharanas"],
    },
    {
        "id": "paris",
        "name": "Paris",
        "country": "France",
        "region": "Europe",
        "tagline": "The clich\u00e9 that never misses.",
        "description": "Yes, everyone goes. There's a reason. Golden-hour Seine walks, croissants that ruin all other croissants, and a tower that still makes cynics look up.",
        "image": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
        "base_price": 1799,
        "rating": 4.8,
        "duration_days": 6,
        "highlights": ["Eiffel Tower champagne hour at dusk", "Louvre before-hours private entry", "Montmartre atelier walk", "Seine dinner cruise"],
    },
    {
        "id": "rome",
        "name": "Rome",
        "country": "Italy",
        "region": "Europe",
        "tagline": "Every street is a museum that serves pasta.",
        "description": "Gladiator arenas, fountains you throw wishes into, carbonara defended like national security. Rome stacked three thousand years of drama and called it a city.",
        "image": "https://images.unsplash.com/photo-1552832230-c0197dd311b5",
        "base_price": 1699,
        "rating": 4.8,
        "duration_days": 6,
        "highlights": ["Colosseum underground access", "Vatican at dawn \u2014 Sistine nearly empty", "Trastevere pasta masterclass", "Vespa golden-hour loop"],
    },
    {
        "id": "cape-town",
        "name": "Cape Town",
        "country": "South Africa",
        "region": "Africa",
        "tagline": "Where two oceans argue and everybody wins.",
        "description": "A flat-topped mountain guarding beaches, penguins with prime real estate, winelands twenty minutes from surf. Cape Town got an unfair share of everything.",
        "image": "https://images.unsplash.com/photo-1576485375217-d6a95e34d043",
        "base_price": 1899,
        "rating": 4.8,
        "duration_days": 8,
        "highlights": ["Table Mountain cableway at sunset", "Boulders Beach penguin colony", "Cape Point coastal drive", "Stellenbosch wine estate day"],
    },
    {
        "id": "queenstown",
        "name": "Queenstown",
        "country": "New Zealand",
        "region": "Oceania",
        "tagline": "Adrenaline's home address.",
        "description": "Bungee jumping was literally invented here. Jet boats, fjords from Middle-earth, mountains that look photoshopped. Queenstown dares you to sit still. You won't.",
        "image": "https://images.unsplash.com/photo-1669123565088-2c71f61ef6a3",
        "base_price": 2199,
        "rating": 4.9,
        "duration_days": 8,
        "highlights": ["Nevis bungee \u2014 134m of commitment", "Milford Sound overnight cruise", "Shotover jet boat canyon run", "Skyline gondola dinner"],
    },
    {
        "id": "petra",
        "name": "Petra",
        "country": "Jordan",
        "region": "Middle East",
        "tagline": "A city carved into a mountain. Casually.",
        "description": "Walk a kilometer-long canyon and watch the Treasury explode into view, carved from rose-red rock two thousand years ago. Petra makes modern architecture look lazy.",
        "image": "https://images.unsplash.com/photo-1554357475-accb8a88a330",
        "base_price": 1499,
        "rating": 4.9,
        "duration_days": 5,
        "highlights": ["The Siq walk to the Treasury reveal", "Petra by Night \u2014 1,500 candles", "Monastery hike (800 steps of glory)", "Wadi Rum desert camp under stars"],
    },
    {
        "id": "bora-bora",
        "name": "Bora Bora",
        "country": "French Polynesia",
        "region": "Oceania",
        "tagline": "The lagoon that invented the color blue.",
        "description": "An extinct volcano wrapped in a turquoise lagoon, villas standing on stilts over water so clear it feels illegal. Bora Bora is the final boss of honeymoons.",
        "image": "https://images.pexels.com/photos/34095820/pexels-photo-34095820.jpeg",
        "base_price": 3499,
        "rating": 5.0,
        "duration_days": 7,
        "highlights": ["Overwater villa with lagoon slide-in", "Mount Otemanu 4x4 safari", "Coral garden snorkel with rays", "Private motu picnic"],
    },
    {
        "id": "agra",
        "name": "Agra",
        "country": "India",
        "region": "India",
        "tagline": "The world's greatest love letter, in marble.",
        "description": "The Taj Mahal at sunrise turns pink, then gold, then impossible. Four centuries of legend, one skyline-stopping monument. Agra is proof that some flexes are eternal.",
        "image": "https://images.unsplash.com/photo-1598324789736-4861f89564a0",
        "base_price": 699,
        "rating": 4.9,
        "duration_days": 4,
        "highlights": ["Taj Mahal at sunrise \u2014 first ones in", "Agra Fort throne rooms", "Mehtab Bagh sunset view across the river", "Mughlai food trail in the old city"],
    },
    {
        "id": "rishikesh",
        "name": "Rishikesh",
        "country": "India",
        "region": "India",
        "tagline": "Find yourself. Or lose yourself in the rapids.",
        "description": "Yoga capital of the world by morning, white-water adrenaline factory by noon, Ganga aarti fires by night. Rishikesh heals you and scares you in the same day.",
        "image": "https://images.unsplash.com/photo-1530866495561-507c9faab2ed",
        "base_price": 649,
        "rating": 4.7,
        "duration_days": 5,
        "highlights": ["Grade IV rapids on the Ganges", "Sunrise yoga on the riverbank", "Lakshman Jhula caf\u00e9 crawl", "Cliff jumping + riverside camping"],
    },
    {
        "id": "manali",
        "name": "Manali",
        "country": "India",
        "region": "India",
        "tagline": "Where the road ends and the Himalayas begin.",
        "description": "Snow ridgelines, pine forests, apple orchards and passes that touch 4,000 meters. Manali is base camp for every mountain daydream you've ever had.",
        "image": "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23",
        "base_price": 749,
        "rating": 4.8,
        "duration_days": 6,
        "highlights": ["Rohtang / Atal tunnel snow day", "Solang Valley paragliding", "Old Manali caf\u00e9s and riverside walks", "Hidimba temple in the deodar forest"],
    },
    {
        "id": "jaisalmer",
        "name": "Jaisalmer",
        "country": "India",
        "region": "India",
        "tagline": "A golden city rising out of the Thar.",
        "description": "A living sandstone fort, havelis carved like lace, and dunes that glow amber at dusk. Jaisalmer is what happens when a desert decides to show off.",
        "image": "https://images.unsplash.com/photo-1542401886-65d6c61db217",
        "base_price": 849,
        "rating": 4.8,
        "duration_days": 5,
        "highlights": ["Sam dunes sunset camel safari", "Night in a desert camp under the stars", "Jaisalmer Fort \u2014 a fort people still live in", "Patwon ki Haveli carved mansions"],
    },
    {
        "id": "andaman",
        "name": "Andaman Islands",
        "country": "India",
        "region": "India",
        "tagline": "India's best-kept turquoise secret.",
        "description": "Radhanagar beach glowing at sunset, coral gardens teeming with life, bioluminescent water after dark. The Andamans feel like the Maldives before the crowds found it.",
        "image": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
        "base_price": 1199,
        "rating": 4.9,
        "duration_days": 6,
        "highlights": ["Radhanagar beach \u2014 Asia's finest sunset", "Scuba at Havelock's coral walls", "Bioluminescence night kayak", "Cellular Jail light & sound story"],
    },
    {
        "id": "darjeeling",
        "name": "Darjeeling",
        "country": "India",
        "region": "India",
        "tagline": "Tea in hand. Kanchenjunga on the horizon.",
        "description": "A toy train chugging through cloud-forest, tea estates rolling to the horizon, and the world's third-highest peak turning gold at dawn. Darjeeling is slow living at altitude.",
        "image": "https://images.unsplash.com/photo-1544735716-392fe2489ffa",
        "base_price": 799,
        "rating": 4.7,
        "duration_days": 5,
        "highlights": ["Tiger Hill sunrise over Kanchenjunga", "Darjeeling Himalayan toy train ride", "Tea estate tasting with the planters", "Batasia Loop + monastery walk"],
    },
]

QUOTES = [
    {"text": "Jobs fill your pocket. Adventures fill your soul.", "author": "Jaime Lyn Beatty"},
    {"text": "You have exactly one life. Stop scrolling through other people's.", "author": "TRAVELO"},
    {"text": "The world is a book and those who do not travel read only one page.", "author": "Saint Augustine"},
    {"text": "Buy the ticket. Apologize to your savings account later.", "author": "TRAVELO"},
    {"text": "Travel is the only thing you buy that makes you richer.", "author": "Anonymous"},
    {"text": "Wander often. Wonder always.", "author": "Anonymous"},
    {"text": "Your comfort zone is a beautiful place, but nothing ever grows there.", "author": "Anonymous"},
    {"text": "Collect moments, not things. Moments don't need dusting.", "author": "TRAVELO"},
    {"text": "Not all those who wander are lost.", "author": "J.R.R. Tolkien"},
    {"text": "We travel not to escape life, but for life not to escape us.", "author": "Anonymous"},
    {"text": "The mountains don't care about your excuses.", "author": "TRAVELO"},
    {"text": "Take only memories, leave only footprints.", "author": "Chief Seattle"},
    {"text": "Life is short and the world is wide. Do the math.", "author": "TRAVELO"},
    {"text": "To travel is to live.", "author": "Hans Christian Andersen"},
    {"text": "Somewhere on Earth, the sun is setting perfectly. You're missing it.", "author": "TRAVELO"},
    {"text": "Adventure is worthwhile in itself.", "author": "Amelia Earhart"},
    {"text": "A ship in harbor is safe, but that is not what ships are built for.", "author": "John A. Shedd"},
    {"text": "Wi-Fi is weaker where the views are stronger. That's the deal.", "author": "TRAVELO"},
    {"text": "Travel far enough, you meet yourself.", "author": "David Mitchell"},
    {"text": "The best stories are found between the pages of a passport.", "author": "Anonymous"},
    {"text": "Airports have seen more sincere kisses than wedding halls.", "author": "Anonymous"},
    {"text": "Quit your excuses. Keep your layovers.", "author": "TRAVELO"},
    {"text": "Once a year, go someplace you've never been before.", "author": "Dalai Lama"},
    {"text": "You can always make money. You can't always make memories.", "author": "TRAVELO"},
    {"text": "I haven't been everywhere, but it's on my list.", "author": "Susan Sontag"},
    {"text": "Travel makes one modest. You see what a tiny place you occupy in the world.", "author": "Gustave Flaubert"},
    {"text": "We wander for distraction, but we travel for fulfilment.", "author": "Hilaire Belloc"},
    {"text": "Live your life by a compass, not a clock.", "author": "Stephen Covey"},
    {"text": "Blessed are the curious, for they shall have adventures.", "author": "Lovelle Drachman"},
    {"text": "A passport full of stamps beats a wall full of certificates.", "author": "TRAVELO"},
    {"text": "Oh, the places you'll go!", "author": "Dr. Seuss"},
    {"text": "Better to see something once than hear about it a thousand times.", "author": "Asian Proverb"},
    {"text": "Tan lines fade. The stories never do.", "author": "TRAVELO"},
    {"text": "Man cannot discover new oceans unless he has the courage to lose sight of the shore.", "author": "Andr\u00e9 Gide"},
    {"text": "Some beautiful paths can't be discovered without getting lost.", "author": "Erol Ozan"},
    {"text": "Your bed is a trap. The horizon is the escape route.", "author": "TRAVELO"},
    {"text": "Traveling \u2014 it leaves you speechless, then turns you into a storyteller.", "author": "Ibn Battuta"},
    {"text": "The journey of a thousand miles begins with a single step.", "author": "Lao Tzu"},
    {"text": "Eat local. Get lost. Trust strangers. Repeat.", "author": "TRAVELO"},
    {"text": "Nobody ever lay on their deathbed wishing they'd stayed home more.", "author": "TRAVELO"},
]
