"""TRAVELO destination catalog + savage quotes — single source of truth."""

TIER_MULTIPLIERS = {"explorer": 1.0, "elite": 1.65, "legend": 2.8}
TIERS = ["explorer", "elite", "legend"]


def tier_price(base_price: int, tier: str) -> int:
    """Price per person in whole USD for a tier."""
    return int(round(base_price * TIER_MULTIPLIERS[tier]))


DESTINATIONS = [
    {
        "id": "santorini",
        "name": "Santorini",
        "country": "Greece",
        "region": "Europe",
        "tagline": "Where the sun dies beautifully every single night.",
        "description": "Cliff-carved villages in blinding white, caldera sunsets that make grown adults cry, and wine grown in volcanic ash. Santorini isn't a destination — it's a flex.",
        "image": "https://images.unsplash.com/photo-1672622851784-0dbd3df4c088",
        "base_price": 1499,
        "rating": 4.9,
        "duration_days": 6,
        "highlights": ["Oia sunset from a private cliff terrace", "Catamaran raid across the caldera", "Volcanic-ash vineyard tasting", "Red Beach cliff dive"],
    },
    {
        "id": "kyoto",
        "name": "Kyoto",
        "country": "Japan",
        "region": "Asia",
        "tagline": "Ten thousand gates. Zero regrets.",
        "description": "Vermilion torii tunnels, bamboo forests that whisper, geisha districts frozen in time. Kyoto is what happens when a city decides perfection is the minimum standard.",
        "image": "https://images.unsplash.com/photo-1665706896821-319040b81753",
        "base_price": 1799,
        "rating": 4.9,
        "duration_days": 7,
        "highlights": ["Fushimi Inari at dawn — before the crowds exist", "Private tea ceremony in Gion", "Arashiyama bamboo grove", "Kaiseki dinner with a Michelin ghost"],
    },
    {
        "id": "iceland",
        "name": "Iceland",
        "country": "Iceland",
        "region": "Europe",
        "tagline": "The sky is on fire and it's completely normal.",
        "description": "Aurora storms overhead, glaciers you can walk inside, black sand beaches that look like another planet. Iceland doesn't do subtle.",
        "image": "https://images.unsplash.com/photo-1518156959312-07a5380c1261",
        "base_price": 1899,
        "rating": 4.8,
        "duration_days": 6,
        "highlights": ["Northern lights hunt in a super-jeep", "Ice cave descent under Vatnajökull", "Blue Lagoon midnight float", "Golden Circle full assault"],
    },
    {
        "id": "bali",
        "name": "Bali",
        "country": "Indonesia",
        "region": "Asia",
        "tagline": "Paradise with a caffeine addiction.",
        "description": "Emerald rice terraces, cliff temples guarded by monkeys with attitude, sunsets that reset your soul. Bali is the reset button you keep pretending you don't need.",
        "image": "https://images.pexels.com/photos/3067621/pexels-photo-3067621.jpeg",
        "base_price": 1199,
        "rating": 4.7,
        "duration_days": 8,
        "highlights": ["Tegallalang rice terrace sunrise", "Uluwatu cliff temple at golden hour", "Private villa with infinity pool", "Nusa Penida island raid"],
    },
    {
        "id": "swiss-alps",
        "name": "Swiss Alps",
        "country": "Switzerland",
        "region": "Europe",
        "tagline": "The mountains called. We answered for you.",
        "description": "The Matterhorn staring you down, trains that climb through clouds, fondue at 3,000 meters. Switzerland charges premium because it IS premium.",
        "image": "https://images.unsplash.com/photo-1640535258715-2cb15ccd7eae",
        "base_price": 2299,
        "rating": 4.9,
        "duration_days": 7,
        "highlights": ["Matterhorn sunrise from Gornergrat", "Glacier Express panoramic ride", "Zermatt heli-tour", "Alpine spa with peak views"],
    },
    {
        "id": "patagonia",
        "name": "Patagonia",
        "country": "Chile",
        "region": "South America",
        "tagline": "Where the map runs out and legends begin.",
        "description": "Granite towers ripping through storm clouds, turquoise glacier lakes, wind that rearranges your priorities. Patagonia is the final boss of landscapes.",
        "image": "https://images.unsplash.com/photo-1637580980556-085dee659c7e",
        "base_price": 2499,
        "rating": 4.8,
        "duration_days": 9,
        "highlights": ["Torres del Paine W-trek (guided)", "Grey Glacier ice hike", "Puma tracking with rangers", "Estancia asado under the stars"],
    },
    {
        "id": "marrakech",
        "name": "Marrakech",
        "country": "Morocco",
        "region": "Africa",
        "tagline": "A thousand colors. One racing heartbeat.",
        "description": "Labyrinth souks, rooftop mint tea, desert nights an hour away. Marrakech doesn't ask for your attention — it takes it.",
        "image": "https://images.pexels.com/photos/36209321/pexels-photo-36209321.jpeg",
        "base_price": 999,
        "rating": 4.6,
        "duration_days": 5,
        "highlights": ["Medina raid with a local fixer", "Agafay desert dinner camp", "Traditional hammam ritual", "Jardin Majorelle private hour"],
    },
    {
        "id": "maldives",
        "name": "Maldives",
        "country": "Maldives",
        "region": "Asia",
        "tagline": "Fifty shades of blue. Zero shades of stress.",
        "description": "Overwater villas, water so clear it looks rendered, reef sharks as neighbors. The Maldives is what screensavers dream of becoming.",
        "image": "https://images.unsplash.com/photo-1514282401047-d79a71a590e8",
        "base_price": 2999,
        "rating": 5.0,
        "duration_days": 6,
        "highlights": ["Overwater villa with glass floor", "Manta ray night snorkel", "Sandbank private picnic", "Sunset dolphin cruise"],
    },
    {
        "id": "machu-picchu",
        "name": "Machu Picchu",
        "country": "Peru",
        "region": "South America",
        "tagline": "The Incas built it. You just have to show up.",
        "description": "A lost city floating in cloud forest at 2,430 meters. Machu Picchu is proof that humans used to build things worth crossing the planet for.",
        "image": "https://images.unsplash.com/photo-1526392060635-9d6019884377",
        "base_price": 1699,
        "rating": 4.9,
        "duration_days": 7,
        "highlights": ["Sunrise entry through the Sun Gate", "Sacred Valley + Pisac market", "Vistadome panoramic train", "Cusco colonial quarter stay"],
    },
    {
        "id": "dubai",
        "name": "Dubai",
        "country": "UAE",
        "region": "Middle East",
        "tagline": "The future got impatient and built itself a city.",
        "description": "Skyscrapers that ignore physics, desert dunes at the city limits, luxury as a baseline. Dubai is what ambition looks like with an unlimited budget.",
        "image": "https://images.pexels.com/photos/36813102/pexels-photo-36813102.jpeg",
        "base_price": 1599,
        "rating": 4.7,
        "duration_days": 5,
        "highlights": ["Burj Khalifa 148th floor lounge", "Desert safari + dune bashing", "Marina superyacht evening", "Old Dubai gold souk raid"],
    },
    {
        "id": "norwegian-fjords",
        "name": "Norwegian Fjords",
        "country": "Norway",
        "region": "Europe",
        "tagline": "Carved by ice. Claimed by you.",
        "description": "Kilometer-deep fjords, waterfalls falling from the sky, villages clinging to cliffs. Norway is nature showing off and refusing to apologize.",
        "image": "https://images.pexels.com/photos/15979078/pexels-photo-15979078.jpeg",
        "base_price": 2099,
        "rating": 4.8,
        "duration_days": 7,
        "highlights": ["Geirangerfjord silent electric cruise", "Trolltunga guided hike", "Flåm railway descent", "Fjordside cabin with sauna"],
    },
    {
        "id": "tokyo",
        "name": "Tokyo",
        "country": "Japan",
        "region": "Asia",
        "tagline": "Thirty-seven million people. Zero wasted seconds.",
        "description": "Neon canyons, sushi masters with 40-year obsessions, silence in temples two blocks from chaos. Tokyo is the maximum possible city.",
        "image": "https://images.unsplash.com/photo-1536768139911-e290a59011e4",
        "base_price": 1899,
        "rating": 4.8,
        "duration_days": 7,
        "highlights": ["Shibuya crossing from a private rooftop", "Tsukiji dawn omakase", "TeamLab digital art night", "Golden Gai bar crawl with a local"],
    },
]

QUOTES = [
    {"text": "Jobs fill your pocket. Adventures fill your soul.", "author": "Jaime Lyn Beatty"},
    {"text": "You have exactly one life. Stop scrolling through other people's.", "author": "TRAVELO"},
    {"text": "The world is a book and those who do not travel read only one page.", "author": "Saint Augustine"},
    {"text": "Buy the ticket. Apologize to your savings account later.", "author": "TRAVELO"},
    {"text": "Travel is the only thing you buy that makes you richer.", "author": "Anonymous"},
    {"text": "Wander often. Wonder always.", "author": "Anonymous"},
    {"text": "Your comfort zone is a beautiful place, but nothing ever grows there.", "author": "Anonymous"},
    {"text": "Collect moments, not things. Moments don't need dusting.", "author": "TRAVELO"},
    {"text": "Not all those who wander are lost.", "author": "J.R.R. Tolkien"},
    {"text": "We travel not to escape life, but for life not to escape us.", "author": "Anonymous"},
    {"text": "The mountains don't care about your excuses.", "author": "TRAVELO"},
    {"text": "Take only memories, leave only footprints.", "author": "Chief Seattle"},
    {"text": "Life is short and the world is wide. Do the math.", "author": "TRAVELO"},
    {"text": "To travel is to live.", "author": "Hans Christian Andersen"},
    {"text": "Somewhere on Earth, the sun is setting perfectly. You're missing it.", "author": "TRAVELO"},
    {"text": "Adventure is worthwhile in itself.", "author": "Amelia Earhart"},
    {"text": "A ship in harbor is safe, but that is not what ships are built for.", "author": "John A. Shedd"},
    {"text": "Wi-Fi is weaker where the views are stronger. That's the deal.", "author": "TRAVELO"},
    {"text": "Travel far enough, you meet yourself.", "author": "David Mitchell"},
    {"text": "The best stories are found between the pages of a passport.", "author": "Anonymous"},
    {"text": "Airports have seen more sincere kisses than wedding halls.", "author": "Anonymous"},
    {"text": "Quit your excuses. Keep your layovers.", "author": "TRAVELO"},
    {"text": "Once a year, go someplace you've never been before.", "author": "Dalai Lama"},
    {"text": "You can always make money. You can't always make memories.", "author": "TRAVELO"},
]
